################################################################################
# panel.yaml — LVGL Editor C Export 測試專案
# Waveshare ESP32-S3-Touch-LCD-7 (800x480)
# 目的：驗證 ui/ui.h + ui/ui.c 整合進 ESPHome 的完整流程
################################################################################
esphome:
  name: "panel"
  friendly_name: "中控時鐘"
  # ── 把 LVGL Editor export 的 .h 和 .c 引入 ──────────────
  includes:
    - ui/ui.h
    - ui/ui.c
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM -DLV_FONT_MONTSERRAT_16=1 -DLV_FONT_MONTSERRAT_20=1 -DLV_FONT_MONTSERRAT_28=1"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288
    board_upload.maximum_size: 8388608
  # ── LVGL 初始化完成後，呼叫 ui.c 裡的 ui_init() ─────────
  on_boot:
    priority: -200       # 最低優先度 = 最後執行，確保 display/lvgl 已就緒
    then:
      - lambda: |-
          ui_init();     // ui.h 宣告的初始化函數

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_LCD_RGB_ISR_IRAM_SAFE: y
      CONFIG_LCD_RGB_RESTART_IN_VSYNC: y
      CONFIG_ESP_WIFI_IRAM_OPT: y
      CONFIG_ESP_WIFI_RX_IRAM_OPT: y
      CONFIG_LWIP_IRAM_OPTIMIZATION: y

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: USB_SERIAL_JTAG

################################################################################
# WiFi
################################################################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  ap:
    ssid: "Panel Fallback"
    password: "12345678"

captive_portal:

################################################################################
# Home Assistant API & OTA
################################################################################
api:
  encryption:
    key: "pEwy8GN+BENS8ot4DDh6GnePUKqBkfaaesO3Nohflrs="

ota:
  - platform: esphome
    password: "f8d96e097cbcb1d5e275d5f8d5f50102"

################################################################################
# I2C + CH422G IO Expander
################################################################################
i2c:
  sda: GPIO08
  scl: GPIO09
  scan: true
  id: bus_a

ch422g:
  - id: ch422g_hub

################################################################################
# 背光
################################################################################
output:
  - platform: gpio
    id: backlight_output
    pin:
      ch422g: ch422g_hub
      number: 2
      mode:
        output: true
      inverted: false

light:
  - platform: binary
    output: backlight_output
    id: display_backlight
    name: "Display Backlight"
    restore_mode: ALWAYS_ON

################################################################################
# Display — Waveshare ESP32-S3-Touch-LCD-7
################################################################################
display:
  - platform: mipi_rgb
    model: ESP32-S3-TOUCH-LCD-7-800X480
    id: my_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 14MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    reset_pin:
      ch422g: ch422g_hub
      number: 3
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      red:   [1, 2, 42, 41, 40]
      blue:  [14, 38, 18, 17, 10]
      green: [39, 0, 45, 48, 47, 21]

################################################################################
# 觸控 — GT911
################################################################################
touchscreen:
  platform: gt911
  id: my_touch
  interrupt_pin: GPIO4
  reset_pin:
    ch422g: ch422g_hub
    number: 1
    mode: OUTPUT

################################################################################
# LVGL — 只負責初始化 display/touch/framebuffer
# UI widget 全部由 ui.c 的 ui_init() 建立
################################################################################
lvgl:
  color_depth: 16
  buffer_size: 15%
  log_level: WARN
  bg_color: 0x0A0E1A
  displays:
    - my_display
  touchscreens:
    - touchscreen_id: my_touch

################################################################################
# 從 HA 取得溫度 → 更新 ui.c 裡的 label_temperature
################################################################################
sensor:
  - platform: homeassistant
    id: ha_indoor_temp
    entity_id: sensor.livingroom_ac_livingroom_temp
    on_value:
      then:
        - lambda: |-
            // 直接操作 ui.c export 的全域指標
            if (label_temperature != nullptr) {
              char buf[32];
              snprintf(buf, sizeof(buf), "Temp: %.1f°C", x);
              lv_label_set_text(label_temperature, buf);
            }

################################################################################
# 每 100ms 輪詢 btn_light_pressed 旗標 → 觸發 HA action
# ui.c 的 button callback 設定旗標，ESPHome 這裡負責呼叫 HA
################################################################################
interval:
  - interval: 100ms
    then:
      - lambda: |-
          extern volatile bool btn_light_pressed;
          if (btn_light_pressed) {
            btn_light_pressed = false;
            id(ha_light_toggle).press();
          }

################################################################################
# ESPHome Template Button — 呼叫 HA service
################################################################################
button:
  - platform: template
    name: "Light Toggle"
    id: ha_light_toggle
    on_press:
      - homeassistant.action:
          action: light.toggle
          data:
            entity_id: light.ke_ting
